# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triptricks', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200)),
                ('number_days', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('sub_destination', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
