# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triptricks', '0005_auto_20170914_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
